In [6]:
import numpy as np
import random
from typing import List

矩阵乘法

In [3]:
# 矩阵乘法
def matrix_matual(A :List[List[int]], B: List[List[int]]) -> List[List[int]]:
    """二维矩阵的乘法
    A: m*n
    B: q*t
    """
    m, n = len(A), len(A[0])
    q, t = len(B), len(B[0])

    assert n == q, "A 的列数不等于 B 的行数"
    res = [[0] * t for _ in range(m)]

    for i in range(0, m):
        for j in range(t):
            for k in range(n):
                res[i][j] += A[i][k] * B[k][j]

    return res   

In [4]:
# 测试
# test 
A = np.random.randint(3, 30, (4,7))
B = np.random.randint(6, 100, (7, 3))

res_np = np.matmul(A, B)
res_my = matrix_matual(A.tolist(), B.tolist())

print(res_np, res_my)

[[6556 4815 6888]
 [7786 6142 8096]
 [8897 6233 8530]
 [5769 4557 7724]] [[6556, 4815, 6888], [7786, 6142, 8096], [8897, 6233, 8530], [5769, 4557, 7724]]


圆周率 $\pi$ 的计算

In [11]:
def calculate_pi(iter_nums: int = 10000) -> float:
    """ 蒙特卡洛方法计算 圆周率 \pi
    """
    hit = 0
    for _ in range(iter_nums):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)

        if x ** 2 + y ** 2 <= 1:
            hit += 1

    pi = 4 * hit / iter_nums

    return pi 

In [15]:
calculate_pi(1000000)

3.140292

三门问题

出自美国的电视游戏节目，参赛者面前有三扇关闭着的门，其中一扇的后面是一辆汽车，而另外两扇门后面则各藏有一只山羊，选中后面有车的那扇门就可以赢得该汽车

当参赛者选定了一扇门，但未去开启它的时候，主持人会开启剩下两扇门中的一扇，露出其中一只山羊。然后问参赛者要不要改变选择，选另一扇仍然关着的门？

在主持人告知一个错误值后：
+ 不改变原选择，胜率仍为1/3
+ 改变选择，胜率会从1/3骤增至2/3
即原先猜中错误项的概率转为猜中正确项的概率

主持人的动作，实际上是在你要换门之前，排除一个错误选项。

只有第一次选对了，不换才能中奖。 第一次选错，换才能中奖。第一次选对的概率是0.33，
所以换比不换合适。

有n个备选答案，其中1个是对的，n-1个都是错的，比较以下两种方案选中正确答案的概率：
1. 一开始选定1个答案，不换。
2. 一开始选定1个答案，不要，接着排除掉1个错误答案后，在剩下的n-2个备选答案里再选1个。

方案1赢的概率： $\frac{1}{n}$

方案 2 赢的概率为 $\frac{1}{n} * 0 (选对了，但是换了) + \frac{n-1}n * \frac{1}{n-2}(选中了错的，然后排除掉1个，再换掉，就是n-2里选1)  = \frac{n-1}{n*(n-2)}$

In [40]:
def three_door(doors: List[str] = ['goat','goat','car'], iter_nums: int = 1000000, change: bool = False) -> float:
    hit_0 = 0
    hit_1 = 0

    if change is False:
        for _ in range(iter_nums):
            idx = random.randint(0, 2)
            if doors[idx] == "car":
                hit_0 += 1
    
        return hit_0 / iter_nums

    else:
        # 有山羊的门
        goat_door = [i for i in range(3) if doors[i] == "goat"]
        
        for _ in range(iter_nums):
            idx = random.randint(0, 2)
            
            # 支持人选择一扇门 山羊的门 
            temp_idx = random.randint(0, len(goat_door)-1)
            while temp_idx == idx:
                temp_idx = random.randint(0, len(goat_door)-1)

            # 换的门 是 剩下了的 一扇门
            idx = 3 - idx - temp_idx
            if doors[idx] == "car":
                hit_1 += 1

        return hit_1 / iter_nums

In [41]:
doors = ['goat','goat','car']

random.shuffle(doors)
prop_0 = three_door(change=False)
prop_1 = three_door(change=True)

print(prop_0, prop_1)

0.332514 0.666611
